name: carpeyom
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+9

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_document_reader_api: ^6.9.2
  flutter_document_reader_core_fullrfid: ^6.9.0
  flutter_face_api: ^5.2.3
  flutter_face_core: ^5.2.0
  flutter_image_compress: ^2.1.0
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  flutter_stories: ^0.3.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  intl: ^0.19.0
  pausable_timer: ^3.1.0+3
  percent_indicator: ^4.2.3
  pinput: ^3.0.1
  dropdown_button2: ^2.3.9
  country_code_picker: ^3.0.0
  permission_handler: ^11.3.0
  geolocator: ^11.0.0

dev_dependencies:
  flutter_flavorizr: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  rename: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/backgrounds/
    - assets/images/banners/
    - assets/fonts/
    - assets/regula.license

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
